Add display of population information
pacificclimate/scip-frontend pull request #36
Opened 2023-07-07 16:23 UTC by corviday

This PR incorporates data about the location of salmon populations from the SCIP backend into the front end and displays it as a table. 

It also removes geoserver from the system - the SCIP backend is replacing that functionality.

resolves #35 
resolves #25

2023-07-07 18:52 UTC, corviday commented
a UI question:

pink salmon subgroups are "odd" and "even" in the data files and in the database, but would we find it clearer if the website said "odd year" and "even year"?

2023-07-11 18:05 UTC, rod-glover reviewed
Great work. 

I see a lot of care with object naming, which is so important for maintenance. 

Code style is variable and kind of idiosyncratic; I think a pass through [ESLint](https://eslint.org/) would be a good idea. Many IDE's have an ESLint plugin that makes this easy. See climate-explorer-frontend for an example of use.

2023-07-11 18:05 UTC, rod-glover commented
Argh, review not complete. Please wait.

2023-07-11 18:22 UTC, rod-glover requested changes
Definitely looking good. I have only one substantive change request:
- I think `useEffect` is being misused in one place.

Code style definitely needs some attention. That would be better in a separate PR. I was going to create an issue, but I see you already have one. It might be really helpful to you to look at ESLint integration into your IDE; I find it so.

2023-07-11 18:22 UTC, rod-glover commented on src/components/PopulationTable/PopulationTable.js
> +    }
Nice to pull out the meaning with the name!

This need not be a function though. You can just calculate a derived value, and simplify code:

```
const noSalmonHere = Array.isArray(populations) && populations.length===0;
```

2023-07-11 18:22 UTC, rod-glover commented on package.json
> +    "Lee Zeman <lzeman@uvic.ca>",
Don't be so modest! You're the primary author, put yourself at the top.

2023-07-11 19:07 UTC, rod-glover commented
I've put further UI feedback in the issue for that #34 . That way when/if others do the same it can all be in one place.

2023-07-12 19:42 UTC, corviday commented on src/components/PopulationTable/PopulationTable.js
> +  }, [populations]);
It featured in all the sample code documentation for AgGridReact, the toolkit I used for the table, but I must have misunderstood the sample code.

2023-07-12 22:11 UTC, rod-glover approved these changes
LGTM!

2023-07-12 23:04 UTC, eyvorchuk approved these changes
Looks good to me overall! Would you be able to make the "Name" column bigger in the Salmon Populations table? The longer names get cut off.

2023-07-13 00:16 UTC, corviday commented
Hey @eyvorchuk , that's a great suggestion! I did that.
![tablespace](https://github.com/pacificclimate/scip-frontend/assets/4512605/15c2000a-afcc-475c-b574-94d9380c0505)

2023-07-13 00:19 UTC, merged