Hierarchical area selection
pacificclimate/scip-frontend pull request #42
Opened 2023-08-03 14:23 UTC by corviday

Allows users to navigate area selection via hierarchical dropdowns. 

There is now a "basin" dropdown, with which a user can select a river basin like "Fraser" or "Nass". This has two effects: it will highlight the entire basin on the map and display salmon population data for the entire basin, and it will populate the conservation unit and watershed dropdowns with conservation units or watersheds that are inside that basin.

Demo [here](https://services.pacificclimate.org/dev/scip/app/).

**Possibly confusing data limitations that will show up in the demo:**

At present, we only have indicator/variable data for the Fraser Basin. Salmon population data is available for all watersheds, but graphs and stream networks are only available within the Fraser. Additionally, watersheds are not defined according to stream networks, so the stream network of a selected watershed may extend outside the watershed.

Also some regions have odd names containing brackets; these were present in the shapefiles I received and I do not know whether to update them.

Conservation unit and watershed shapes are from different data sources, and sometimes "adjacent" regions are treated as nesting; fixing this probably involved updating the backend to accepts a minimum overlapping area term.

Future work:
This is part one of a two- or three-part overhaul of area selection. Part two will allow users to further narrow down the list of possible watersheds or conservation units by specifying one or more salmon species they are interested in. 

resolves #3

2023-08-03 17:12 UTC, rod-glover commented
Question: Are the watersheds supposed to be entirely inside the basins? Or is just a bit of overlap that makes it elegible?

Example:
1. Select Fraser River basin.
2. Select Babine Lake watershed. It has only a very small overlap with Fraser basin. At far zoom outs, it looks like no overlap.

2023-08-03 17:27 UTC, corviday commented
Watersheds _should_ be entirely inside basins, but obviously aren't. I believe the correct fix for this involves changing the backend defines with "overlaps" - that is, setting some minimum area required in order for two shapes to be considered overlapping.

2023-08-03 22:28 UTC, rod-glover commented
Ah, that makes more sense. Maybe a minimum fraction of area of overlap. What the denominator should be is an interesting question: minimum of the two? sum of the two?

2023-09-02 19:05 UTC, rod-glover requested changes
This works very nicely! It looks as if the Basin and Species selectors do what they're supposed to.

Some broader questions/comments (maybe to be addressed elsewhere):
1. When are the other river basins going to receive data? It might be good to disable them in the Basin dropdown until they do have data. It's quite confusing for a naive user (that's me) to select a basin with no data - the white outline is very hard to spot against only the base map.
2. Did you say you were having trouble with layout of the checkboxes? It looks like you may. If so, may I suggest letting React Bootstrap do the layout work for you? Specifically, you can use a[ `<ButtonToolbar>`](https://react-bootstrap.github.io/docs/components/button-group) to enclose a set of [`<Form.Check type="checkbox" />` ](https://react-bootstrap.github.io/docs/forms/checks-radios)items. Example:
```
    <ButtonToolbar aria-label="Basic example">
      {[1,2,3,4,5,6].map(i => (<Form.Check type={"checkbox"} id={`foo`} label={`Your amazing salmon species ${i}`}  className="me-2"/>))}
    </ButtonToolbar>
```
This lays out the checkboxes horizontally (for some reason `ButtonGroup` doesn't, but this does.) The `me-2` is a [helper class](https://getbootstrap.com/docs/4.0/utilities/spacing/) that adds margins to items it's applied to, so the checkboxes are spaced nicely. You could choose a different helper class. 

Of course you'll map the `taxons` array, not integers.

I think it would be worth discussing these things:
1. When and where to introduce state in a React component.
2. When to use and not use `useEffect`.
3. Computing values derived from props and state inside a component. It's actually pleasingly simple.

2023-09-02 19:16 UTC, rod-glover commented on src/components/AreaDisplay/AreaDisplay.js
> +  }
This is an optional change. More FYI than a change request.

2023-09-06 16:54 UTC, corviday commented
>     1. When are the other river basins going to receive data? It might be good to disable them in the Basin dropdown until they do have data. It's quite confusing for a naive user (that's me) to select a basin with no data - the white outline is very hard to spot against only the base map.

Data for coastal regions is very nearly ready. Data for the interior might be a year off.

2023-09-07 00:54 UTC, corviday commented on src/components/TaxonSelector/TaxonCheckbox.js
> +
ah, yes, thank you. That's much better!

2023-09-07 19:25 UTC, corviday commented
> Did you say you were having trouble with layout of the checkboxes? It looks like you may. If so, may I suggest letting React Bootstrap do the layout work for you? Specifically, you can use a[ <ButtonToolbar>](https://react-bootstrap.github.io/docs/components/button-group) to enclose a set of [<Form.Check type="checkbox" /> ](https://react-bootstrap.github.io/docs/forms/checks-radios)items.

I am having layout troubles! Can I get your opinion on these options, various combinations of your suggestions of `ButtonToolbar` and `me-2`:

current layout, as a reminder:
![current](https://github.com/pacificclimate/scip-frontend/assets/4512605/3ae7a434-bccb-491e-bc20-3977eec31f1c)

Changing to `ButtonToolbar` and `me-2` and keeping everything else constant - doesn't quite work because the labels are too long:
![toolbar](https://github.com/pacificclimate/scip-frontend/assets/4512605/346d4893-226d-4ce6-94da-547ebf8e54ad)

Using `ButtonToolbar` and `me-2`, and putting the taxon checkboxes in their own Row, instead of sharing with the basin dropdown:
![taxonrow](https://github.com/pacificclimate/scip-frontend/assets/4512605/43573f1a-1e3f-422f-b4f3-5999c7e6a8b8)

Using only `me-2` to keep the current layout, but with nice spacing:
![me-2only](https://github.com/pacificclimate/scip-frontend/assets/4512605/f30c775e-331d-4986-b399-4cd3c4f23a97)

I think I prefer the last option, but would like your opinion. Is there something else I should consider for this layout?

2023-09-07 21:20 UTC, rod-glover commented
I like the last option best. It also looks like you've put each item into a <Col>, which gives a nice lineup with the row below.

Side note: If you want (not suggesting you need it), you can increase the spacing between checkboxes by using `me-3` or higher. There is an abundance of nice helper classes in Bootstrap, and I love it when I realize I can just use them instead of crafting my own. Plus they always work right!

2023-09-07 21:23 UTC, corviday commented
Yeah! I tried adding margins with CSS, but it didn't work; I'm sure I was doing something wrong. me-2 is _easy_!

2023-09-07 23:46 UTC, corviday commented on src/components/AreaDisplay/AreaDisplay.js
> +      }
Yes, but the backend "give me all watersheds" call is _significantly_ faster and easier than making seven "give me chum watersheds, give me coho watersheds, etc" calls and merging the results - not only is the latter seven separate calls with a fair bit of overlap in the results, but each call contains a spatial join between the region table where watershed geometries are and the conservation unit table of where salmon are.

The empty list case is redundant, though, I'll get rid of that one and document the reasoning on the other.

2023-09-08 00:26 UTC, corviday commented
I have improved the formatting on the checkboxes and fixed the React lifecycle issues.

2023-09-08 16:54 UTC, rod-glover approved these changes
LGTM! A few minor items for you to consider, but all good.

Some observations/questions on the UI:
- When you change the species selection, the previous watershed or conservation unit selection remains, even if it is invalid. (Easiest way to see this is to select a watershed, deselect all species; watershed is still selected even tho the option list is now empty.) Probably changing species should also remove those selections.
- I think a Select All and Clear All control for the species would be helpful. You could use buttons, or that trick where a single checkbox is used, but it might be trickier to implement.
- I wonder if it might be better to place the dropdown labels on the same line as the dropdowns, at least for larger layouts. Or maybe you could use the lovely [Floating labels](https://react-bootstrap.github.io/docs/forms/floating-labels) feature of React Bootstrap. I mean particularly for the basin, watershed, and conservation unit selectors, although it applies equally to all drop
- (I know this isn't directly related to this PR, but this should probably go into an issue to be addressed.) On the Yearly Indicators tab, there is no default value for Climate Model or Emissions Scenario, yet when you select a Variable, you see a graph. What model and emissions are used for that graph? It should show up in the selectors. Same for Monthly Indicators, Daily Indicators, Salmon Populations.

2023-09-08 16:54 UTC, rod-glover commented on src/components/AreaDisplay/AreaDisplay.js
> +          getBasins().then(
Possible bug here: If the backend returns a zero-length list, then you enter an infinite loop of requests. Unlikely but not strictly speaking impossible.

2023-09-08 16:54 UTC, rod-glover commented on src/components/TaxonSelector/TaxonCheckbox.js
> +//        <label>
Remove commented out lines?

2023-09-08 16:54 UTC, rod-glover commented on src/helpers/GeographyHelpers.js
> +        && p.type === "Point"
You can squish the previous three lines down to `p?.type === "Point"`, using the [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator.

2023-09-08 16:54 UTC, rod-glover commented on src/helpers/GeographyHelpers.js
> +        && _.isNumber(p.coordinates[1]);
And the series of `&&`s here can become `_.isNumber(p?.coordinates?.[0]) && _.isNumber(p?.coordinates?.[1])`

2023-09-11 19:46 UTC, corviday commented
I was hoping to implement some of the excellent UI suggestions "quickly" but it took long enough I think it belongs in a separate PR, so I have just done the chaining operator suggestions. I didn't know about that, thanks!

2023-09-11 23:01 UTC, merged