Update indicator data
pacificclimate/scip-frontend pull request #56
Opened 2023-10-25 20:43 UTC by corviday

Updates the portal to use the new indicator (netCDF raster) data including coastal regions and further North along the Skeena and Nass basins.

Also implements a whitelist for the predefined watersheds and basins from the BC Freshwater Atlas and predefined salmon conservation units from DFO. Only regions for which we have data will be visible in the dropdowns.

resolves #51 
resolves #40 (incidentally, by switching to an entirely new dataset)
resolves #55

2023-10-25 23:38 UTC, rod-glover commented
Good call on the linting. I suggest a separate PR (not needing review probably) for linting, each time the project overall needs it. Minor linting can be incorporated in larger PR's of course.

2023-10-26 00:14 UTC, rod-glover requested changes
Great work so far. One coding suggestion. 

And a question about either data or logic: In the demo, if I select any basin, the watersheds available are always the same. Basin does not affect that selector. Ditto for CU. Is that intended?

2023-10-26 00:14 UTC, rod-glover commented on src/helpers/GeographyHelpers.js
> +    const filter = whitelist ? whitelistFilter : identityFilter;
Nice.

2023-10-26 00:42 UTC, corviday commented on public/basins.yaml
> +# coverage of.
My thinking was:

There are two separate databases, one modelmeta database that contains file information about the gridded netCDF database. There is one postGIS database that contains the names and boundaries of the regions.

This list describes the overlap between them - which of the regions in the region database overlap with the availability of gridded data in the indicator database. So it isn't clearly a property of _either_ database, and the natural location for it is this Javascript app, which uses _both_ databases and cares about the spatial relationships between them.

Does that make sense?

2023-10-26 00:51 UTC, corviday commented
> And a question about either data or logic: In the demo, if I select any basin, the watersheds available are always the same. Basin does not affect that selector. Ditto for CU. Is that intended?

Oops, no! I will look into that.

2023-10-26 17:01 UTC, corviday commented
Hm, it is working "correctly" for me; selecting different basins shows different watersheds and conservation units. Could you perhaps clear your cache and try again?

2023-10-26 18:03 UTC, rod-glover commented
Cleared cache, now watersheds for each basin are mostly disjoint. Fraser and Skeena basins share at least Babine Lake and Babine River watersheds. But they are adjacent and I suspect the polygons overlap in an unfortunate way and that this is a data problem not a logic problem.

That said, the need to clear cache will have to be eliminated at some point. Users won't know to do that.

2023-10-26 18:04 UTC, rod-glover commented
Some 500 errors occur from time to time in the console (and network, of course) log. I can't quite figure out what is provoking them but suspect that invalid or insufficient arguments are being provided to the endpoints. Which are, so far, 

- https://services.pacificclimate.org/dev/scip/api/region?kind=watershed
- https://services.pacificclimate.org/dev/scip/api/region?kind=conservation_unit
- https://services.pacificclimate.org/dev/pcex/api/streamflow/downstream?station=POINT+(-123.117+49.098)&ensemble_name=fraser_bccoast_watershed

This might not be a thing you need to address immediately.

2023-10-26 18:05 UTC, rod-glover commented on public/basins.yaml
> +# coverage of.
That definitely makes sense.

2023-10-30 17:48 UTC, rod-glover approved these changes
Great work!

2023-10-30 17:55 UTC, merged