Push a docker to dockerhub
pacificclimate/scip-frontend pull request #73
Opened 2024-06-15 03:35 UTC by corviday

This app has not previously been on dockerhub, and has needed to be built locally for each deployment. Added a github workflow that publishes the docker container.

Resolves #26

2024-06-17 23:20 UTC, corviday commented
[Demo appears to have built correctly.](https://services.pacificclimate.org/dev/scip/app/)

2024-06-19 20:41 UTC, rod-glover requested changes
A few suggestions. Best to keep our tooling versions up to date as much as possible. Otherwise this looks file.

2024-06-19 20:41 UTC, rod-glover commented on .github/workflows/docker-publish.yml
> +    runs-on: ubuntu-20.04
We should be using 22.04. This will go stale fast. Might as well be up to date now.

2024-06-19 20:41 UTC, rod-glover commented on .github/workflows/docker-publish.yml
> +      - uses: actions/checkout@v2
There's a v4 version of this. Let's use it.

2024-06-19 20:41 UTC, rod-glover commented on .github/workflows/docker-publish.yml
> +        uses: docker/build-push-action@v1
v6

2024-06-19 20:41 UTC, rod-glover commented on .github/workflows/docker-publish.yml
> +          tag_with_ref: true
I think you need to add

```
build_args: REACT_APP_APP_VERSION=${{ env.REACT_APP_APP_VERSION }}
```

to allow the frontend build to see this value.

2024-06-22 00:39 UTC, merged